spring.application.name=taskmanagement-api-springboot

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanagementApi
spring.datasource.username=enockcode
spring.datasource.password=enock1

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true